04 - TheBigBark WebUI/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _04___TheBigBark_WebUI.Models;
using Microsoft.AspNet.Identity;
using YE;

namespace _04___TheBigBark_WebUI.Controllers
{
    public class AppointmentsController : Controller
    {

        private AppointmentsBL logic = new AppointmentsBL();

        // GET: Appointments
        [Authorize()]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            List<AppointmentModel> appointments = logic.GetUserAppointments(userId).ToSelectedList(ViewModelExtensions.ToView);
            return View(appointments);
        }

        // GET: Appointments1/Create
        public ActionResult Create()
        {
            //var users= new UsersBL().GetAll();
            //ViewBag.UserId = new SelectList(users, "Id", "Email");
            return View();
        }

        // POST: Appointments1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Date")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                //db.Appointments.Add(appointment);
                //db.SaveChanges();
                var bl = new AppointmentsBL();
                appointment.UserId = User.Identity.GetUserId();
                bl.Add(appointment);
                return RedirectToAction("Index");
            }

            //var users = new UsersBL().GetAll();
            //ViewBag.UserId = new SelectList(users, "Id", "Email");
            return View(appointment);
        }

        [Authorize()]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = new AppointmentsBL().Get(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        [Authorize()]
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AppointmentsBL appointmentsBl = new AppointmentsBL();
            appointmentsBl.Remove(id);
            return RedirectToAction("Index");
        }

        //ADMIN AREA::::
        //GET: Appointments
        [Authorize(Roles = "Administrators")]
        public ActionResult AdminIndex(DateTime? sDate = null, DateTime? eDate = null, string name = null)
        {
            List<SelectAllAppointments_Result> dbAppointments = logic.GetAll(sDate, eDate, name);
            List<AppointmentModel> x = dbAppointments.ToSelectedList(ViewModelExtensions.ToView);
            return View("AdminIndex", x);
        }
    }
}

04 - TheBigBark WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _04___TheBigBark_WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //public
            if (!User.Identity.IsAuthenticated)
            {
                return View("PublicIndex");
            }

            //admin
            if (User.IsInRole("Administrators"))
            {
                return View("AdminIndex");
            }

            //normal user
            return View("Index");
        }

      
        [Route("Home/About")]
        public ActionResult About()
        {
            ViewBag.Message = "TheBig Bark is a barber shop for animals the best in town.";

            return View();
        }

        [Route("Home/Contact")]
        public ActionResult Contact()
        {
            ViewBag.Message = "contact the big bark manager.";

            return View();
        }



        //ADMIN AREA::::
        //[Authorize(Roles = "Administrator")]
        //public ActionResult AdminIndex()
        //{
        //    return
        //}

    }
}

04 - TheBigBark WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>please register to our site and you will know more</p>

04 - TheBigBark WebUI/Views/Home/AdminIndex.cshtml
@using YE

@{
    ViewBag.Title = "Index";
}

    <div class="main">

        <h2 align="center">Admin Home Page</h2>

        @Html.ActionLink("Add Appointment", "Create", "Appointments")
        <br />
        <a href="https://localhost:44369/Users">Show All Users</a>
        <br />
        <a href="https://localhost:44369/Appointments/AdminIndex">Show All Appointments</a>

    </div>

04 - TheBigBark WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Harav mordechai eliyaho 6/26<br />
    Lod, Israel<br />
    <abbr title="Phone">P:</abbr>
    052-525-3955
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@TheBigBark.com</a>
    <br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@TheBigBark.com</a>
</address>

04 - TheBigBark WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>

    body {
        background-image: url(https://static.independent.co.uk/s3fs-public/thumbnails/image/2019/09/04/13/istock-1031307988.jpg?w968);
        background-repeat: no-repeat;
        /*background-attachment: fixed;*/
        background-size: cover;
    }

    h1 {
        margin-top: 10px
    }

    div.main {
    }
</style>

<a href="https://localhost:44369/Appointments">Show All Of Youre Appointment</a>

<div class="main">
    @Html.ActionLink("Add Appointment", "Create", "Appointments")
</div>

04 - TheBigBark WebUI/Views/Home/PublicIndex.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>
 
    body {
        background-image: url(https://static.independent.co.uk/s3fs-public/thumbnails/image/2019/09/04/13/istock-1031307988.jpg?w968);
        background-repeat: no-repeat;
        /*background-attachment: fixed;*/
        background-size: cover;
    }

    h1 {
        margin-top: 10px
    }

</style>


<div class="main">
    <h1 align="center" style="accelerator: initial">Welcome to the big bark store</h1>
    <h2 align="center">Please register to our website!</h2>
    <h3 align="center">If you already registered, please log in!</h3>

</div>